=== Lemme-lab/Project-Wuldor/Code/Microcontroller Code/Robotic-Arm-ESP32/lib/rl-0.7.0/examples/rlkin/rlkin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="elementType">
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="frameType">
		<xs:complexContent>
			<xs:extension base="elementType">
				<xs:sequence>
					<xs:element name="rotation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="translation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="jointType">
		<xs:complexContent>
			<xs:extension base="transformType">
				<xs:sequence>
					<xs:element name="center" type="xs:double" minOccurs="0"/>
					<xs:element name="dh">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="d" type="xs:double"/>
								<xs:element name="theta" type="xs:double"/>
								<xs:element name="a" type="xs:double"/>
								<xs:element name="alpha" type="xs:double"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="max" type="xs:double" minOccurs="0"/>
					<xs:element name="min" type="xs:double" minOccurs="0"/>
					<xs:element name="offset" type="xs:double" minOccurs="0"/>
					<xs:element name="speed" type="xs:double" minOccurs="0"/>
					<xs:element name="wraparound" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="kinematicsType">
		<xs:sequence>
			<xs:element name="manufacturer" type="xs:string" minOccurs="0"/>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="world" type="worldType" minOccurs="1"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="frame" type="frameType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="link" type="linkType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="prismatic" type="prismaticType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="revolute" type="revoluteType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="transform" type="transformType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="linkType">
		<xs:complexContent>
			<xs:extension base="frameType">
				<xs:sequence>
					<xs:element name="ignore" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name="idref" type="xs:IDREF"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="prismaticType">
		<xs:complexContent>
			<xs:extension base="jointType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="pumaType">
		<xs:sequence>
			<xs:element name="manufacturer" type="xs:string" minOccurs="0"/>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="world" type="worldType" minOccurs="1"/>
			<xs:element name="transform" type="transformType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="revolute" type="revoluteType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="revolute" type="revoluteType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="revolute" type="revoluteType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="revolute" type="revoluteType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="revolute" type="revoluteType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="revolute" type="revoluteType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="transform" type="transformType" minOccurs="1"/>
			<xs:element name="frame" type="frameType" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="revoluteType">
		<xs:complexContent>
			<xs:extension base="jointType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="rhinoType">
		<xs:sequence>
			<xs:element name="manufacturer" type="xs:string" minOccurs="0"/>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="world" type="worldType" minOccurs="1"/>
			<xs:element name="transform" type="transformType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="revolute" type="revoluteType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="revolute" type="revoluteType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="revolute" type="revoluteType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="revolute" type="revoluteType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="revolute" type="revoluteType" minOccurs="1"/>
			<xs:element name="link" type="linkType" minOccurs="1"/>
			<xs:element name="transform" type="transformType" minOccurs="1"/>
			<xs:element name="frame" type="frameType" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="rl">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="kin">
					<xs:complexType>
						<xs:choice>
							<xs:element name="kinematics" type="kinematicsType"/>
							<xs:element name="puma" type="pumaType"/>
							<xs:element name="rhino" type="rhinoType"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="rlkin">
		<xs:complexType>
			<xs:choice>
				<xs:element name="kinematics" type="kinematicsType"/>
				<xs:element name="puma" type="pumaType"/>
				<xs:element name="rhino" type="rhinoType"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="transformType">
		<xs:complexContent>
			<xs:extension base="elementType">
				<xs:sequence>
					<xs:element name="frame">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="a">
									<xs:complexType>
										<xs:attribute name="idref" type="xs:IDREF"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="b">
									<xs:complexType>
										<xs:attribute name="idref" type="xs:IDREF"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="rotation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="translation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="worldType">
		<xs:complexContent>
			<xs:extension base="frameType"/>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== Lemme-lab/Project-Wuldor/Code/Microcontroller Code/Robotic-Arm-ESP32/lib/rl-0.7.0/examples/rlkin/staeubli-tx60l.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlkin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlkin.xsd">
	<puma>
		<manufacturer>St√§ubli</manufacturer>
		<name>TX-60L</name>
		<world id="world">
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</world>
		<transform id="base">
			<frame>
				<a idref="world"/>
				<b idref="link0"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</transform>
		<link id="link0">
			<ignore/>
			<ignore idref="link1"/>
		</link>
		<revolute id="joint0">
			<frame>
				<a idref="link0"/>
				<b idref="link1"/>
			</frame>
			<dh>
				<d>0.375</d>
				<theta>0</theta>
				<a>0</a>
				<alpha>-90</alpha>
			</dh>
			<max>180</max>
			<min>-180</min>
		</revolute>
		<link id="link1">
			<ignore idref="link0"/>
			<ignore idref="link2"/>
		</link>
		<revolute id="joint1">
			<frame>
				<a idref="link1"/>
				<b idref="link2"/>
			</frame>
			<dh>
				<d>0</d>
				<theta>-90</theta>
				<a>0.4</a>
				<alpha>0</alpha>
			</dh>
			<max>127.5</max>
			<min>-127.5</min>
		</revolute>
		<link id="link2">
			<ignore idref="link1"/>
			<ignore idref="link3"/>
			<ignore idref="link4"/>
		</link>
		<revolute id="joint2">
			<frame>
				<a idref="link2"/>
				<b idref="link3"/>
			</frame>
			<dh>
				<d>0.02</d>
				<theta>-90</theta>
				<a>0</a>
				<alpha>-90</alpha>
			</dh>
			<max>152.5</max>
			<min>-152.5</min>
		</revolute>
		<link id="link3">
			<ignore idref="link2"/>
			<ignore idref="link4"/>
		</link>
		<revolute id="joint3">
			<frame>
				<a idref="link3"/>
				<b idref="link4"/>
			</frame>
			<dh>
				<d>0.45</d>
				<theta>0</theta>
				<a>0</a>
				<alpha>90</alpha>
			</dh>
			<max>270</max>
			<min>-270</min>
		</revolute>
		<link id="link4">
			<ignore idref="link2"/>
			<ignore idref="link3"/>
			<ignore idref="link5"/>
			<ignore idref="link6"/>
		</link>
		<revolute id="joint4">
			<frame>
				<a idref="link4"/>
				<b idref="link5"/>
			</frame>
			<dh>
				<d>0</d>
				<theta>180</theta>
				<a>0</a>
				<alpha>90</alpha>
			</dh>
			<max>133.5</max>
			<min>-122.5</min>
		</revolute>
		<link id="link5">
			<ignore idref="link4"/>
			<ignore idref="link6"/>
		</link>
		<revolute id="joint5">
			<frame>
				<a idref="link5"/>
				<b idref="link6"/>
			</frame>
			<dh>
				<d>0.07</d>
				<theta>0</theta>
				<a>0</a>
				<alpha>0</alpha>
			</dh>
			<max>270</max>
			<min>-270</min>
		</revolute>
		<link id="link6">
			<ignore idref="link4"/>
			<ignore idref="link5"/>
		</link>
		<transform id="tool">
			<frame>
				<a idref="link6"/>
				<b idref="tcp"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</transform>
		<frame id="tcp"/>
	</puma>
</rlkin>

=== Lemme-lab/Project-Wuldor/Code/Microcontroller Code/Robotic-Arm-ESP32/lib/rl-0.7.0/examples/rlkin/box-6d-300505.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlkin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlkin.xsd">
	<kinematics>
		<manufacturer></manufacturer>
		<name>6D Box (3.0m x 0.5m x 0.5m)</name>
		<world id="world">
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</world>
		<transform id="base">
			<frame>
				<a idref="world"/>
				<b idref="link0"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>90</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</transform>
		<link id="link0">
			<ignore/>
			<ignore idref="link1"/>
			<ignore idref="link2"/>
			<ignore idref="link3"/>
			<ignore idref="link4"/>
			<ignore idref="link5"/>
		</link>
		<prismatic id="joint0">
			<frame>
				<a idref="link0"/>
				<b idref="link1"/>
			</frame>
			<dh>
				<d>0</d>
				<theta>0</theta>
				<a>0</a>
				<alpha>-90</alpha>
			</dh>
			<max>30</max>
			<min>0</min>
		</prismatic>
		<link id="link1">
			<ignore/>
			<ignore idref="link0"/>
			<ignore idref="link2"/>
			<ignore idref="link3"/>
			<ignore idref="link4"/>
			<ignore idref="link5"/>
		</link>
		<prismatic id="joint1">
			<frame>
				<a idref="link1"/>
				<b idref="link2"/>
			</frame>
			<dh>
				<d>0</d>
				<theta>-90</theta>
				<a>0</a>
				<alpha>90</alpha>
			</dh>
			<max>30</max>
			<min>0</min>
		</prismatic>
		<link id="link2">
			<ignore/>
			<ignore idref="link0"/>
			<ignore idref="link1"/>
			<ignore idref="link3"/>
			<ignore idref="link4"/>
			<ignore idref="link5"/>
		</link>
		<prismatic id="joint2">
			<frame>
				<a idref="link2"/>
				<b idref="link3"/>
			</frame>
			<dh>
				<d>0</d>
				<theta>90</theta>
				<a>0</a>
				<alpha>90</alpha>
			</dh>
			<max>2</max>
			<min>0</min>
		</prismatic>
		<link id="link3">
			<ignore/>
			<ignore idref="link0"/>
			<ignore idref="link1"/>
			<ignore idref="link2"/>
			<ignore idref="link4"/>
			<ignore idref="link5"/>
		</link>
		<revolute id="joint3">
			<frame>
				<a idref="link3"/>
				<b idref="link4"/>
			</frame>
			<dh>
				<d>0</d>
				<theta>-90</theta>
				<a>0</a>
				<alpha>-90</alpha>
			</dh>
			<max>180</max>
			<min>-180</min>
			<wraparound/>
		</revolute>
		<link id="link4">
			<ignore/>
			<ignore idref="link0"/>
			<ignore idref="link1"/>
			<ignore idref="link2"/>
			<ignore idref="link3"/>
			<ignore idref="link5"/>
		</link>
		<revolute id="joint4">
			<frame>
				<a idref="link4"/>
				<b idref="link5"/>
			</frame>
			<dh>
				<d>0</d>
				<theta>-90</theta>
				<a>0</a>
				<alpha>90</alpha>
			</dh>
			<max>90</max>
			<min>-90</min>
		</revolute>
		<link id="link5">
			<ignore/>
			<ignore idref="link0"/>
			<ignore idref="link1"/>
			<ignore idref="link2"/>
			<ignore idref="link3"/>
			<ignore idref="link4"/>
		</link>
		<revolute id="joint5">
			<frame>
				<a idref="link5"/>
				<b idref="link6"/>
			</frame>
			<dh>
				<d>0</d>
				<theta>0</theta>
				<a>0</a>
				<alpha>0</alpha>
			</dh>
			<max>180</max>
			<min>-180</min>
			<wraparound/>
		</revolute>
		<link id="link6">
			<ignore idref="link0"/>
			<ignore idref="link1"/>
			<ignore idref="link2"/>
			<ignore idref="link3"/>
			<ignore idref="link4"/>
			<ignore idref="link5"/>
		</link>
		<transform id="tool">
			<frame>
				<a idref="link6"/>
				<b idref="tcp"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>1.5</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</transform>
		<frame id="tcp"/>
	</kinematics>
</rlkin>
