=== Lemme-lab/Project-Wuldor/Code/Microcontroller Code/Robotic-Arm-ESP32/lib/rl-0.7.0/examples/rlmdl/rlmdl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="bodyType">
		<xs:complexContent>
			<xs:extension base="frameType">
				<xs:sequence>
					<xs:element name="cm" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="i" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="xx" type="xs:double" minOccurs="0"/>
								<xs:element name="yy" type="xs:double" minOccurs="0"/>
								<xs:element name="zz" type="xs:double" minOccurs="0"/>
								<xs:element name="yz" type="xs:double" minOccurs="0"/>
								<xs:element name="xz" type="xs:double" minOccurs="0"/>
								<xs:element name="xy" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="ignore" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name="idref" type="xs:IDREF"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="m" type="xs:double" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="cylindricalType">
		<xs:complexContent>
			<xs:extension base="jointType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="elementType">
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="fixedType">
		<xs:complexContent>
			<xs:extension base="transformType">
				<xs:sequence>
					<xs:element name="rotation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="translation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="frameType">
		<xs:complexContent>
			<xs:extension base="elementType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="gammaType">
		<xs:sequence>
			<xs:element name="row" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="col" type="xs:double" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="helicalType">
		<xs:complexContent>
			<xs:extension base="jointType">
				<xs:sequence>
					<xs:element name="pitch" type="xs:double" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="homeType">
		<xs:sequence>
			<xs:element name="q" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:double">
							<xs:attribute name="unit">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="deg"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="jointType">
		<xs:complexContent>
			<xs:extension base="transformType">
				<xs:sequence>
					<xs:element name="axis" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="max" type="xs:double" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="min" type="xs:double" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="offset" type="xs:double" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="speed" type="xs:double" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="wraparound" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="modelType">
		<xs:sequence>
			<xs:element name="manufacturer" type="xs:string" minOccurs="0"/>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="world" type="worldType" minOccurs="1"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="body" type="bodyType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="cylindrical" type="cylindricalType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="fixed" type="fixedType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="frame" type="frameType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="gamma" type="gammaType" minOccurs="0"/>
				<xs:element name="helical" type="helicalType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="home" type="homeType" minOccurs="0"/>
				<xs:element name="prismatic" type="prismaticType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="revolute" type="revoluteType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="spherical" type="sphericalType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="prismaticType">
		<xs:complexContent>
			<xs:extension base="jointType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="revoluteType">
		<xs:complexContent>
			<xs:extension base="jointType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="rl">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="mdl">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="model" type="modelType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="rlmdl">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="model" type="modelType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="sphericalType">
		<xs:complexContent>
			<xs:extension base="jointType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="transformType">
		<xs:complexContent>
			<xs:extension base="elementType">
				<xs:sequence>
					<xs:element name="frame">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="a">
									<xs:complexType>
										<xs:attribute name="idref" type="xs:IDREF"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="b">
									<xs:complexType>
										<xs:attribute name="idref" type="xs:IDREF"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="worldType">
		<xs:complexContent>
			<xs:extension base="frameType">
				<xs:sequence>
					<xs:element name="rotation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="translation" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="g">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="x" type="xs:double" minOccurs="0"/>
								<xs:element name="y" type="xs:double" minOccurs="0"/>
								<xs:element name="z" type="xs:double" minOccurs="0"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== Lemme-lab/Project-Wuldor/Code/Microcontroller Code/Robotic-Arm-ESP32/lib/rl-0.7.0/examples/rlmdl/mitsubishi-rv6sl.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlmdl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlmdl.xsd">
	<model>
		<manufacturer>Mitsubishi</manufacturer>
		<name>RV6-SL</name>
		<world id="world">
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
			<g>
				<x>0</x>
				<y>0</y>
				<z>9.86055</z>
			</g>
		</world>
		<body id="body0">
			<ignore/>
			<ignore idref="body1"/>
		</body>
		<frame id="frame0"/>
		<frame id="frame1"/>
		<body id="body1">
			<ignore idref="body0"/>
			<ignore idref="body2"/>
		</body>
		<frame id="frame2"/>
		<body id="body2">
			<ignore idref="body1"/>
			<ignore idref="body3"/>
			<ignore idref="body4"/>
		</body>
		<frame id="frame3"/>
		<body id="body3">
			<ignore idref="body2"/>
			<ignore idref="body4"/>
		</body>
		<frame id="frame4"/>
		<frame id="frame5"/>
		<body id="body4">
			<ignore idref="body2"/>
			<ignore idref="body3"/>
			<ignore idref="body5"/>
			<ignore idref="body6"/>
		</body>
		<frame id="frame6"/>
		<body id="body5">
			<ignore idref="body4"/>
			<ignore idref="body6"/>
		</body>
		<frame id="frame7"/>
		<body id="body6">
			<ignore idref="body4"/>
			<ignore idref="body5"/>
		</body>
		<frame id="frame8"/>
		<fixed id="fixed0">
			<frame>
				<a idref="world"/>
				<b idref="body0"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<fixed id="fixed1">
			<frame>
				<a idref="body0"/>
				<b idref="frame0"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0.35</z>
			</translation>
		</fixed>
		<revolute id="joint0">
			<frame>
				<a idref="frame0"/>
				<b idref="frame1"/>
			</frame>
			<max>170</max>
			<min>-170</min>
			<speed>250</speed>
		</revolute>
		<fixed id="fixed2">
			<frame>
				<a idref="frame1"/>
				<b idref="body1"/>
			</frame>
			<rotation>
				<x>-90</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0.085</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<revolute id="joint1">
			<frame>
				<a idref="body1"/>
				<b idref="frame2"/>
			</frame>
			<max>135</max>
			<min>-92</min>
			<speed>267</speed>
		</revolute>
		<fixed id="fixed3">
			<frame>
				<a idref="frame2"/>
				<b idref="body2"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>-90</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>-0.38</y>
				<z>0</z>
			</translation>
		</fixed>
		<revolute id="joint2">
			<frame>
				<a idref="body2"/>
				<b idref="frame3"/>
			</frame>
			<max>166</max>
			<min>-129</min>
			<speed>267</speed>
		</revolute>
		<fixed id="fixed4">
			<frame>
				<a idref="frame3"/>
				<b idref="body3"/>
			</frame>
			<rotation>
				<x>-90</x>
				<y>0</y>
				<z>-90</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>-0.1</y>
				<z>0</z>
			</translation>
		</fixed>
		<fixed id="fixed5">
			<frame>
				<a idref="body3"/>
				<b idref="frame4"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0.425</z>
			</translation>
		</fixed>
		<revolute id="joint3">
			<frame>
				<a idref="frame4"/>
				<b idref="frame5"/>
			</frame>
			<max>160</max>
			<min>-160</min>
			<speed>352</speed>
		</revolute>
		<fixed id="fixed6">
			<frame>
				<a idref="frame5"/>
				<b idref="body4"/>
			</frame>
			<rotation>
				<x>90</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<revolute id="joint4">
			<frame>
				<a idref="body4"/>
				<b idref="frame6"/>
			</frame>
			<max>120</max>
			<min>-120</min>
			<speed>450</speed>
		</revolute>
		<fixed id="fixed7">
			<frame>
				<a idref="frame6"/>
				<b idref="body5"/>
			</frame>
			<rotation>
				<x>90</x>
				<y>0</y>
				<z>180</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<fixed id="fixed8">
			<frame>
				<a idref="body5"/>
				<b idref="frame7"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0.085</z>
			</translation>
		</fixed>
		<revolute id="joint5">
			<frame>
				<a idref="frame7"/>
				<b idref="body6"/>
			</frame>
			<max>360</max>
			<min>-360</min>
			<speed>660</speed>
		</revolute>
		<fixed id="fixed9">
			<frame>
				<a idref="body6"/>
				<b idref="frame8"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
	</model>
</rlmdl>

=== Lemme-lab/Project-Wuldor/Code/Microcontroller Code/Robotic-Arm-ESP32/lib/rl-0.7.0/examples/rlmdl/planar2.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlmdl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlmdl.xsd">
	<model>
		<manufacturer>Featherstone</manufacturer>
		<name>planar2</name>
		<world id="frame0">
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
			<g>
				<x>0</x>
				<y>0</y>
				<z>9.80665</z>
			</g>
		</world>
		<frame id="frame1"/>
		<body id="frame2">
			<cm>
				<x>0.5</x>
				<y>0</y>
				<z>0</z>
			</cm>
			<i>
				<xx>0.01</xx>
				<yy>0.083333333</yy>
				<zz>0.083333333</zz>
				<yz>0</yz>
				<xz>0</xz>
				<xy>0</xy>
			</i>
			<m>1</m>
		</body>
		<frame id="frame3"/>
		<body id="frame4">
			<cm>
				<x>0.5</x>
				<y>0</y>
				<z>0</z>
			</cm>
			<i>
				<xx>0.01</xx>
				<yy>0.083333333</yy>
				<zz>0.083333333</zz>
				<yz>0</yz>
				<xz>0</xz>
				<xy>0</xy>
			</i>
			<m>1</m>
		</body>
		<frame id="frame5"/>
		<fixed id="link0">
			<frame>
				<a idref="frame0"/>
				<b idref="frame1"/>
			</frame>
			<rotation>
				<x>-90</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>2</z>
			</translation>
		</fixed>
		<revolute id="joint0">
			<frame>
				<a idref="frame1"/>
				<b idref="frame2"/>
			</frame>
		</revolute>
		<fixed id="link1">
			<frame>
				<a idref="frame2"/>
				<b idref="frame3"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>1</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<revolute id="joint1">
			<frame>
				<a idref="frame3"/>
				<b idref="frame4"/>
			</frame>
		</revolute>
		<fixed id="link2">
			<frame>
				<a idref="frame4"/>
				<b idref="frame5"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>1</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
	</model>
</rlmdl>

=== Lemme-lab/Project-Wuldor/Code/Microcontroller Code/Robotic-Arm-ESP32/lib/rl-0.7.0/examples/rlmdl/unimation-puma560.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlmdl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlmdl.xsd">
	<model>
		<manufacturer>Unimation</manufacturer>
		<name>Puma 560</name>
		<world id="world">
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
			<g>
				<x>0</x>
				<y>0</y>
				<z>9.86055</z>
			</g>
		</world>
		<body id="body0">
			<ignore/>
			<ignore idref="body1"/>
		</body>
		<frame id="frame0"/>
		<frame id="frame1"/>
		<body id="body1">
			<cm>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</cm>
			<i>
				<xx>0</xx>
				<yy>0.35</yy>
				<zz>0</zz>
				<yz>0</yz>
				<xz>0</xz>
				<xy>0</xy>
			</i>
			<ignore idref="body0"/>
			<ignore idref="body2"/>
			<m>0</m>
		</body>
		<frame id="frame2"/>
		<body id="body2">
			<cm>
				<x>-0.3638</x>
				<y>0.006</y>
				<z>0.2275</z>
			</cm>
			<i>
				<xx>0.13</xx>
				<yy>0.524</yy>
				<zz>0.539</zz>
				<yz>0</yz>
				<xz>0</xz>
				<xy>0</xy>
			</i>
			<ignore idref="body1"/>
			<ignore idref="body3"/>
			<ignore idref="body4"/>
			<m>17.4</m>
		</body>
		<frame id="frame3"/>
		<body id="body3">
			<cm>
				<x>-0.0203</x>
				<y>-0.0141</y>
				<z>0.07</z>
			</cm>
			<i>
				<xx>0.066</xx>
				<yy>0.086</yy>
				<zz>0.0125</zz>
				<yz>0</yz>
				<xz>0</xz>
				<xy>0</xy>
			</i>
			<ignore idref="body2"/>
			<ignore idref="body4"/>
			<m>4.8</m>
		</body>
		<frame id="frame4"/>
		<body id="body4">
			<cm>
				<x>0</x>
				<y>0.019</y>
				<z>0</z>
			</cm>
			<i>
				<xx>1.8e-3</xx>
				<yy>1.3e-3</yy>
				<zz>1.8e-3</zz>
				<yz>0</yz>
				<xz>0</xz>
				<xy>0</xy>
			</i>
			<ignore idref="body2"/>
			<ignore idref="body3"/>
			<ignore idref="body5"/>
			<ignore idref="body6"/>
			<m>0.82</m>
		</body>
		<frame id="frame5"/>
		<body id="body5">
			<cm>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</cm>
			<i>
				<xx>0.3e-3</xx>
				<yy>0.4e-3</yy>
				<zz>0.3e-3</zz>
				<yz>0</yz>
				<xz>0</xz>
				<xy>0</xy>
			</i>
			<ignore idref="body4"/>
			<ignore idref="body6"/>
			<m>0.34</m>
		</body>
		<frame id="frame6"/>
		<body id="body6">
			<cm>
				<x>0</x>
				<y>0</y>
				<z>0.032</z>
			</cm>
			<i>
				<xx>0.15e-3</xx>
				<yy>0.15e-3</yy>
				<zz>0.04e-3</zz>
				<yz>0</yz>
				<xz>0</xz>
				<xy>0</xy>
			</i>
			<ignore idref="body4"/>
			<ignore idref="body5"/>
			<m>0.09</m>
		</body>
		<frame id="frame7"/>
		<fixed id="fixed0">
			<frame>
				<a idref="world"/>
				<b idref="body0"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<fixed id="fixed1">
			<frame>
				<a idref="body0"/>
				<b idref="frame0"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<revolute id="joint0">
			<frame>
				<a idref="frame0"/>
				<b idref="frame1"/>
			</frame>
			<max>160</max>
			<min>-160</min>
			<speed>320</speed>
		</revolute>
		<fixed id="fixed2">
			<frame>
				<a idref="frame1"/>
				<b idref="body1"/>
			</frame>
			<rotation>
				<x>-90</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0.6604</z>
			</translation>
		</fixed>
		<revolute id="joint1">
			<frame>
				<a idref="body1"/>
				<b idref="frame2"/>
			</frame>
			<max>45</max>
			<min>-225</min>
			<speed>250</speed>
		</revolute>
		<fixed id="fixed3">
			<frame>
				<a idref="frame2"/>
				<b idref="body2"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0.4318</x>
				<y>0</y>
				<z>0.1291</z>
			</translation>
		</fixed>
		<revolute id="joint2">
			<frame>
				<a idref="body2"/>
				<b idref="frame3"/>
			</frame>
			<max>225</max>
			<min>-45</min>
			<speed>270</speed>
		</revolute>
		<fixed id="fixed4">
			<frame>
				<a idref="frame3"/>
				<b idref="body3"/>
			</frame>
			<rotation>
				<x>90</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>-0.0203</x>
				<y>0</y>
				<z>0</z>
			</translation>

		</fixed>
		<revolute id="joint3">
			<frame>
				<a idref="body3"/>
				<b idref="frame4"/>
			</frame>
			<max>170</max>
			<min>-110</min>
			<speed>300</speed>
		</revolute>
		<fixed id="fixed5">
			<frame>
				<a idref="frame4"/>
				<b idref="body4"/>
			</frame>
			<rotation>
				<x>-90</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0.4331</z>
			</translation>
		</fixed>
		<revolute id="joint4">
			<frame>
				<a idref="body4"/>
				<b idref="frame5"/>
			</frame>
			<max>100</max>
			<min>-100</min>
			<speed>200</speed>
		</revolute>
		<fixed id="fixed6">
			<frame>
				<a idref="frame5"/>
				<b idref="body5"/>
			</frame>
			<rotation>
				<x>90</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<revolute id="joint5">
			<frame>
				<a idref="body5"/>
				<b idref="frame6"/>
			</frame>
			<max>266</max>
			<min>-266</min>
			<speed>532</speed>
		</revolute>
		<fixed id="fixed7">
			<frame>
				<a idref="frame6"/>
				<b idref="body6"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0.04125</z>
			</translation>
		</fixed>
	</model>
</rlmdl>

=== Lemme-lab/Project-Wuldor/Code/Microcontroller Code/Robotic-Arm-ESP32/lib/rl-0.7.0/examples/rlmdl/comau-smart5-nj4-220-27.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlmdl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlmdl.xsd">
	<model>
		<manufacturer>Comau</manufacturer>
		<name>SMART5 NJ4 220 2.7</name>
		<world id="world">
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
			<g>
				<x>0</x>
				<y>0</y>
				<z>9.86055</z>
			</g>
		</world>
		<body id="body0">
			<ignore/>
			<ignore idref="body1"/>
		</body>
		<frame id="frame0"/>
		<frame id="frame1"/>
		<body id="body1">
			<ignore idref="body0"/>
			<ignore idref="body2"/>
		</body>
		<frame id="frame2"/>
		<body id="body2">
			<ignore idref="body1"/>
			<ignore idref="body3"/>
			<ignore idref="body4"/>
		</body>
		<frame id="frame3"/>
		<body id="body3">
			<ignore idref="body2"/>
			<ignore idref="body4"/>
		</body>
		<frame id="frame4"/>
		<body id="body4">
			<ignore idref="body2"/>
			<ignore idref="body3"/>
			<ignore idref="body5"/>
			<ignore idref="body6"/>
		</body>
		<frame id="frame5"/>
		<body id="body5">
			<ignore idref="body4"/>
			<ignore idref="body6"/>
		</body>
		<frame id="frame6"/>
		<body id="body6">
			<ignore idref="body4"/>
			<ignore idref="body5"/>
		</body>
		<frame id="frame7"/>
		<fixed id="fixed0">
			<frame>
				<a idref="world"/>
				<b idref="body0"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<fixed id="fixed1">
			<frame>
				<a idref="body0"/>
				<b idref="frame0"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0.83</z>
			</translation>
		</fixed>
		<revolute id="joint0">
			<frame>
				<a idref="frame0"/>
				<b idref="frame1"/>
			</frame>
			<axis>
				<x>0</x>
				<y>0</y>
				<z>-1</z>
			</axis>
			<max>180</max>
			<min>-180</min>
			<speed>100</speed>
		</revolute>
		<fixed id="fixed2">
			<frame>
				<a idref="frame1"/>
				<b idref="body1"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0.4</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<revolute id="joint1">
			<frame>
				<a idref="body1"/>
				<b idref="frame2"/>
			</frame>
			<axis>
				<x>0</x>
				<y>1</y>
				<z>0</z>
			</axis>
			<max>95</max>
			<min>-75</min>
			<speed>90</speed>
		</revolute>
		<fixed id="fixed3">
			<frame>
				<a idref="frame2"/>
				<b idref="body2"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>1.175</z>
			</translation>
		</fixed>
		<revolute id="joint2">
			<frame>
				<a idref="body2"/>
				<b idref="frame3"/>
			</frame>
			<axis>
				<x>0</x>
				<y>-1</y>
				<z>0</z>
			</axis>
			<max>-10</max>
			<min>-256</min>
			<offset>90</offset>
			<speed>110</speed>
		</revolute>
		<fixed id="fixed4">
			<frame>
				<a idref="frame3"/>
				<b idref="body3"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0.25</z>
			</translation>
		</fixed>
		<revolute id="joint3">
			<frame>
				<a idref="body3"/>
				<b idref="frame4"/>
			</frame>
			<axis>
				<x>-1</x>
				<y>0</y>
				<z>0</z>
			</axis>
			<max>200</max>
			<min>-200</min>
			<speed>130</speed>
		</revolute>
		<fixed id="fixed5">
			<frame>
				<a idref="frame4"/>
				<b idref="body4"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>1.165</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<revolute id="joint4">
			<frame>
				<a idref="body4"/>
				<b idref="frame5"/>
			</frame>
			<axis>
				<x>0.5</x>
				<y>0</y>
				<z>0.86602540378443864676372317075294</z>
			</axis>
			<max>200</max>
			<min>-200</min>
			<speed>125</speed>
		</revolute>
		<fixed id="fixed6">
			<frame>
				<a idref="frame5"/>
				<b idref="body5"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0.31</x>
				<y>0</y>
				<z>0.14722</z>
			</translation>
		</fixed>
		<revolute id="joint5">
			<frame>
				<a idref="body5"/>
				<b idref="frame6"/>
			</frame>
			<axis>
				<x>-1</x>
				<y>0</y>
				<z>0</z>
			</axis>
			<max>200</max>
			<min>-200</min>
			<speed>170</speed>
		</revolute>
		<fixed id="fixed7">
			<frame>
				<a idref="frame6"/>
				<b idref="body6"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<fixed id="fixed8">
			<frame>
				<a idref="body6"/>
				<b idref="frame7"/>
			</frame>
			<rotation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</rotation>
			<translation>
				<x>0</x>
				<y>0</y>
				<z>0</z>
			</translation>
		</fixed>
		<home>
			<q unit="deg">0</q>
			<q unit="deg">0</q>
			<q unit="deg">-90</q>
			<q unit="deg">0</q>
			<q unit="deg">0</q>
			<q unit="deg">0</q>
		</home>
		<gamma>
			<row>
				<col>1</col>
				<col>0</col>
				<col>0</col>
				<col>0</col>
				<col>0</col>
				<col>0</col>
			</row>
			<row>
				<col>0</col>
				<col>1</col>
				<col>0</col>
				<col>0</col>
				<col>0</col>
				<col>0</col>
			</row>
			<row>
				<col>0</col>
				<col>1</col>
				<col>1</col>
				<col>0</col>
				<col>0</col>
				<col>0</col>
			</row>
			<row>
				<col>0</col>
				<col>0</col>
				<col>0</col>
				<col>1</col>
				<col>0</col>
				<col>0</col>
			</row>
			<row>
				<col>0</col>
				<col>0</col>
				<col>0</col>
				<col>0</col>
				<col>1</col>
				<col>0</col>
			</row>
			<row>
				<col>0</col>
				<col>0</col>
				<col>0</col>
				<col>0</col>
				<col>0</col>
				<col>1</col>
			</row>
		</gamma>
	</model>
</rlmdl>
