=== Lemme-lab/Project-Wuldor/Code/Microcontroller Code/Robotic-Arm-ESP32/lib/rl-0.7.0/examples/rlsg/rlsg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="bodyType">
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="modelType">
		<xs:sequence>
			<xs:element name="body" type="bodyType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="rl">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sg">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="scene" type="sceneType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="rlsg">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="scene" type="sceneType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="sceneType">
		<xs:sequence>
			<xs:element name="model" type="modelType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="href" type="xs:anyURI" use="required"/>
	</xs:complexType>
</xs:schema>

=== Lemme-lab/Project-Wuldor/Code/Microcontroller Code/Robotic-Arm-ESP32/lib/rl-0.7.0/examples/rlsg/box-6d-300505_maze.xml
<?xml version="1.0" encoding="UTF-8"?>
<rlsg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rlsg.xsd">
	<scene href="box-6d-300505_maze.wrl">
		<model name="box-6d-300505">
			<body name="link0"/>
			<body name="link1"/>
			<body name="link2"/>
			<body name="link3"/>
			<body name="link4"/>
			<body name="link5"/>
			<body name="body1"/>
		</model>
		<model name="maze">
			<body name=""/>
		</model>
	</scene>
</rlsg>
